language: scala

jdk: openjdk8

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

services:
  - docker

before_install:
  - docker-compose up -d virtuoso

script:
  - sbt discoveryJVM/test
