# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2

virtuoso:
  image: askomics/virtuoso:7.2.5.1
  container_name: "virtuoso"
  env_file:
    VIRT_Parameters_NumberOfBuffers: 3400
    VIRT_Parameters_MaxDirtyBuffers: 2500
    VIRT_Parameters_TN_MAX_memory: 400000
    VIRT_SPARQL_ResultSetMaxRows: 10000
    VIRT_SPARQL_MaxDataSourceSize: 100000
    VIRT_Flags_TN_MAX_memory: 40000
    VIRT_Parameters_StopCompilerWhenXOverRunTime: 1
    VIRT_SPARQL_MaxQueryCostEstimationTime: 0
    VIRT_SPARQL_MaxQueryExecutionTime: 300
    VIRT_Parameters_MaxMemPoolSize: 80000
    VIRT_Database_LockFile: virtuoso.lck
    DBA_PASSWORD: dba
    SPARQL_UPDATE: true
    DEFAULT_GRAPH: http://localhost:8890/DAV
  command:
    - /bin/sh
    - -c
    - netstat -nr | grep '^0\.0\.0\.0' | awk '{print $$2 " host "}' >> /etc/hosts && sh /virtuoso/virtuoso.sh
  ports:
    - "8890:8890"
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      # virtuoso
      - run:
          name: Start virtuoso container
          command: |
            set -x
            #docker-compose up -d virtuoso
            sleep 20
            docker ps
            #curl http://localhost:8890/sparql
            #curl http://127.0.0.1:8890/sparql
            #curl http://0.0.0.0.1:8890/sparql

      - run: cat /dev/null | sbt discoveryJVM/test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # run tests!
      - run:
          command: |
            cat /dev/null | sbt clean coverage discoveryJVM/test:test
            docker-compose logs
      # coverage
      - run: sbt discoveryJVM/coverageReport